### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/jinsy-magazine#1]
Lyselma
Yvona
Tiree
Hoenn
Jinsy
Jola
Ronda
Roka
Mera
Yana

Chroma Bay

I've tried a word combiner with these words: Masonry, Blog, Post, Shop, Grid, Parallax
MasBlog
MasonBlog
Masonrost
Masrid
Malax
Masax
Blogost
Gridlog
GriPost
Gallax
Glax
Gax
Paralost

**Comment by radu-themeisle** [comment]
I like Jinsy, or rather Jinxy

From the list these are my top 3:
1. Roka
2. Yana
3. Glax (sounds bit weird though... but it's the only one I like from the list :D )

**Comment by sab2ina** [comment]
@rodica-andronache @stefan-cotitosu if the theme has no special magazine features/layout I am not sure it's a good idea to call it Jinsy _Magazine_. Users might get confused.

**Comment by rodica-andronache** [comment]
the idea here was to showcase it as a magazine theme in the demo and screenshot ( with magazine layouts ). 
otherwise, we don't have much we can do from the child theme.
and Ionut mentioned it's a good idea to use keywords like that in the name.
at least, this is what I am thinking :)
