### ISSUE TITLE
Mention source of images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/jinsy-magazine#21]
https://themes.trac.wordpress.org/ticket/63784#comment:2

**Comment by stefan-cotitosu** [comment]
@rodica-andronache Please check the archive submitted for review. On codeinwp dev/master there is no readme.txt file.

On my fork, the readme.txt file respects the latest format and have the images links.
I've created this pull request.
https://github.com/Codeinwp/jinsy-magazine/pull/22

**Comment by rodica-andronache** [comment]
@stefan-cotitosu you should mention the license CC0 for the self-made images too, and the last image has an extra 's' at the end
